# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^docs/source/generated/
    -   id: end-of-file-fixer
        exclude: ^docs/source/generated/
    -   id: check-yaml
        exclude: ^helm/hams-sample/templates/
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: ['--branch', 'main']
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    # detect-secrets scan > .secrets.baseline
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
