#ifndef hams_h
#define hams_h

/* Generated with cbindgen:0.24.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialise the FFI based logging for this crate
 */
void hams_logger_init(LogParam param);

#endif /* hams_h */
