[package]
name = "hamsrs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "~0.4", features = ["release_max_level_info"] }
ffi-log2 = { path = "../ffi-log2" }
libc = "~0.2"
thiserror = "~1.0"
hams = { path = "../hams"}
